include:
  - project: "mpib/chm/common/deploy-pipeline"
    ref: "1.5.3"
    file: 'common.yml'

variables:
  APP_NAME: creative-ai-app-frontend
  WEB_PORT: 3000
  REPLICA_COUNT: 1
  NEXT_PUBLIC_BACKEND_API: "wss://creative-ai-app-backend.eks-test-default.mpg-chm.com/ws/"

stages:
  - init
  - docker
  - deploy
  - undeploy

init:
  extends: .init-stage

  script:
    - apk add --no-cache git
    - source deploy-pipeline/build_env.sh
    - deploy-pipeline/display_env.sh

  after_script:
    - cp -r $CHILD_PIPELINE_EXECUTION_CONTEXT/* ./
    - rm -rf frontend
    - rm -rf backend
    #    - ls -R
  artifacts:
    paths:
      - ./

docker:
  extends: .docker-stage
  before_script:
    - rm -rf frontend
    - rm -rf backend
    - ls -R

deploy-prod: { extends: .deploy-prod-stage }
deploy-dev: { extends: .deploy-dev-stage }
undeploy: { extends: .undeploy-stage }